<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ddlMartialStatus_Married</name>
   <tag></tag>
   <elementGuidId>4f2a0a64-e3fa-4708-b58d-49425226f975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[24]/div[2]/div[2]/div[1]/ul[1]/li[3]/a[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runtime-list-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;21cfc8b8-257f-4e40-adc4-5390b1a4a855_41c192af-df1c-4068-9576-e48cb6056d03_cdc1a22d-99ac-ce7b-1d4d-0431c4b169cb_a032d094-2e71-40b1-bed9-fae0e5a41af2&quot;)/div[@class=&quot;grid-body&quot;]/div[@class=&quot;grid-body-content&quot;]/div[@class=&quot;grid-body-content-wrapper&quot;]/div[@class=&quot;scroll-wrapper&quot;]/table[@class=&quot;grid-content-table zebra-stripes&quot;]/tbody[1]/tr[@class=&quot;selected highlighted&quot;]/td[@class=&quot;first&quot;]/div[@class=&quot;grid-content-cell&quot;]/div[@class=&quot;grid-content-cell-wrapper&quot;]/span[@class=&quot;runtime-list-item&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Master/iframe_idIframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='21cfc8b8-257f-4e40-adc4-5390b1a4a855_41c192af-df1c-4068-9576-e48cb6056d03_cdc1a22d-99ac-ce7b-1d4d-0431c4b169cb_a032d094-2e71-40b1-bed9-fae0e5a41af2']/div[3]/div[2]/div/div/table/tbody/tr[6]/td/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[4]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOS'])[5]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOS'])[6]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[5]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
